MySmartSCM_APP/eBizSuiteAppUI/Controllers/ServiceReceiptController.cs
using eBizSuiteAppModel.Table;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml;
using WebMatrix.Data;

namespace MeBizSuiteAppUI.Controllers
{
    public class ServiceReceiptController : Controller
    {
        //
        // GET: /ServiceReceipt/

        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["sqlcon"].ToString());
        eBizSuiteTableEntities dc = new eBizSuiteTableEntities();
        CommonController taxlst = new CommonController();
        public ActionResult ServiceCreate()
        {
            try
            {
                Session["POSGridData"] = null;
                //List<SelectListItem> Customer = new List<SelectListItem>();
                //SqlDataAdapter cmddl = new SqlDataAdapter("select COLUMN02,COLUMN05 COLUMN04 from SATABLE002  where  (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND COLUMNA03='" + Session["AcOwner"] + "' and isnull(COLUMN25,'False')='False' and isnull(COLUMNA13,'False')='False'  order by COLUMN02 desc", cn);
                //DataTable dtdata = new DataTable();
                //cmddl.Fill(dtdata);
                //for (int dd = 0; dd < dtdata.Rows.Count; dd++)
                //{
                //    Customer.Add(new SelectListItem { Value = dtdata.Rows[dd]["COLUMN02"].ToString(), Text = dtdata.Rows[dd]["COLUMN04"].ToString() });
                //}
                //ViewData["Customer"] = new SelectList(Customer, "Value", "Text");
                List<SelectListItem> Item = new List<SelectListItem>();
                SqlDataAdapter cmdi = new SqlDataAdapter("select COLUMN02,COLUMN04 from MATABLE007  Where COLUMN04 !='' and  COLUMN05='ITTY009' and (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND COLUMNA03='" + Session["AcOwner"] + "' and isnull(COLUMN47,'False')='False' and  isnull(COLUMNA13,'False')='False'  order by COLUMN02 desc", cn);
                DataTable dti = new DataTable();
                cmdi.Fill(dti);
                for (int dd = 0; dd < dti.Rows.Count; dd++)
                {
                    Item.Add(new SelectListItem { Value = dti.Rows[dd]["COLUMN02"].ToString(), Text = dti.Rows[dd]["COLUMN04"].ToString() });
                }
                ViewData["Item"] = new SelectList(Item, "Value", "Text");
                List<SelectListItem> Customer1 = new List<SelectListItem>();
                SqlDataAdapter cmddld = new SqlDataAdapter("select COLUMN02,COLUMN05,COLUMN04 from SATABLE002  where  (COLUMN40='True' or COLUMN40=1) and COLUMN05 !='' and (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND COLUMNA03='" + Session["AcOwner"] + "' and isnull(COLUMNA13,'False')='False' order by COLUMN05 ", cn);
                DataTable dtdatad = new DataTable();
                cmddld.Fill(dtdatad);
                SqlDataAdapter cmddl1 = new SqlDataAdapter("select COLUMN02,COLUMN05 COLUMN04 from SATABLE002  where  COLUMN05 !='' and (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND COLUMNA03='" + Session["AcOwner"] + "' and isnull(COLUMNA13,'False')='False' order by COLUMN05 ", cn);
                DataTable dtdata1 = new DataTable();
                cmddl1.Fill(dtdata1);
                var DefaultFlag = ""; var DefaultFlagval = "";
                if (dtdatad.Rows.Count > 0) DefaultFlagval = dtdatad.Rows[0]["COLUMN02"].ToString();
                for (int dd = 0; dd < dtdata1.Rows.Count; dd++)
                {
                    if (DefaultFlagval == dtdata1.Rows[dd]["COLUMN02"].ToString())
                        DefaultFlag = dtdata1.Rows[dd]["COLUMN02"].ToString();
                    Customer1.Add(new SelectListItem { Value = dtdata1.Rows[dd]["COLUMN02"].ToString(), Text = dtdata1.Rows[dd]["COLUMN04"].ToString() });
                }
                ViewData["Customer"] = new SelectList(Customer1, "Value", "Text", selectedValue: DefaultFlag);
                List<SelectListItem> Amtin = new List<SelectListItem>();
                SqlDataAdapter cmda = new SqlDataAdapter("select COLUMN02,COLUMN04 from MATABLE002 where column03=11159 AND (COLUMNA03='" + Session["AcOwner"] + "' or isnull(COLUMNA03,0)=0) and isnull(COLUMNA13,'False')='False' order by COLUMN02 desc", cn);
                DataTable dta = new DataTable();
                cmda.Fill(dta);
                for (int dd = 0; dd < dta.Rows.Count; dd++)
                {
                    Amtin.Add(new SelectListItem { Value = dta.Rows[dd]["COLUMN02"].ToString(), Text = dta.Rows[dd]["COLUMN04"].ToString() });
                }
                ViewData["Amtin"] = new SelectList(Amtin, "Value", "Text", selectedValue: Session["TaxInclusive"]);
                //DateFormat();
                ViewBag.DateFormat = Session["FormatDate"];
                List<SelectListItem> Attendedby = new List<SelectListItem>();
                SqlDataAdapter cmdat = new SqlDataAdapter("SELECT COLUMN02,RTRIM(LTRIM(COLUMN09)) COLUMN04 from MATABLE010 where (COLUMN30='True' or COLUMN30=1) and COLUMN09 !='' and (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND COLUMNA03='" + Session["AcOwner"] + "' and isnull(COLUMN32,'False')='False' and  isnull(COLUMNA13,'False')='False'  order by COLUMN09", cn);
                DataTable dtat = new DataTable();
                cmdat.Fill(dtat);
                var salesrep = "";
                for (int dd = 0; dd < dtat.Rows.Count; dd++)
                {
                    if (Convert.ToString(Session["eid"]) == dtat.Rows[dd]["COLUMN02"].ToString())
                        salesrep = dtat.Rows[dd]["COLUMN02"].ToString();
                    Attendedby.Add(new SelectListItem { Value = dtat.Rows[dd]["COLUMN02"].ToString(), Text = dtat.Rows[dd]["COLUMN04"].ToString() });
                }
                ViewData["Attendedby"] = new SelectList(Attendedby, "Value", "Text", selectedValue: salesrep);
                return View();
            }
            catch (Exception ex)
            {
                var msg = "Failed........";
                Session["MessageFrom"] = msg + " Due to " + ex.Message;
                Session["SuccessMessageFrom"] = "fail";
                var idi = "";
                var custform = Request.UrlReferrer.Query.ToString(); custform = custform.Replace("?", ""); int m = custform.IndexOf("&"); if (m > 0) { idi = custform.Substring(0, m).Replace("idi=", "").ToString(); custform = custform.Remove(0, m + 1); } custform = custform.Replace("%20", " "); custform = custform.Replace("FormName=", ""); int n = custform.IndexOf("&"); if (n > 0) { custform = custform.Substring(0, n); }
                return RedirectToAction("Info", "EmployeeMaster", new { idi = idi, FormName = custform });
            }
        }
        public ActionResult ServiceDiscountTypes(string FormName, string Qty, string Price)
        {
            try
            {
                List<SelectListItem> DiscountType = new List<SelectListItem>();
                SqlDataAdapter cmddl = new SqlDataAdapter("select COLUMN02,COLUMN04 from MATABLE002  where COLUMN03=11158 and (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null)   AND (COLUMNA03='" + Session["AcOwner"] + "' or COLUMNA03 is null)  and isnull(COLUMNA13,'False')='False'", cn);
                DataTable dtdata = new DataTable();
                cmddl.Fill(dtdata);
                for (int dd = 0; dd < dtdata.Rows.Count; dd++)
                {
                    DiscountType.Add(new SelectListItem { Value = dtdata.Rows[dd]["COLUMN02"].ToString(), Text = dtdata.Rows[dd]["COLUMN04"].ToString() });
                }
                ViewData["DiscountType"] = new SelectList(DiscountType, "Value", "Text");
                return PartialView("ServiceDiscountTypes");
            }
            catch (Exception ex)
            {
                var msg = "Failed........";
                Session["MessageFrom"] = msg + " Due to " + ex.Message;
                Session["SuccessMessageFrom"] = "fail";
                var idi = "";
                var custform = Request.UrlReferrer.Query.ToString(); custform = custform.Replace("?", ""); int m = custform.IndexOf("&"); if (m > 0) { idi = custform.Substring(0, m).Replace("idi=", "").ToString(); custform = custform.Remove(0, m + 1); } custform = custform.Replace("%20", " "); custform = custform.Replace("FormName=", ""); int n = custform.IndexOf("&"); if (n > 0) { custform = custform.Substring(0, n); }
                return RedirectToAction("Info", "EmployeeMaster", new { idi = idi, FormName = custform });
            }
        }
        public ActionResult ServiceTaxInformation(string ItemId, string Customer, string FormName, string Qty, string Price, string Date)
        {
            try
            {
                List<SelectListItem> TaxType = new List<SelectListItem>();
                //SqlDataAdapter cmddl = new SqlDataAdapter("select COLUMN02,COLUMN04 from MATABLE013	where (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null) AND (COLUMNA03='" + Session["AcOwner"] + "' or COLUMNA03 is null) and isnull(COLUMN15,0)=0 and isnull(COLUMNA13,0)=0 and column16 in(22401,23582,23584,23583,23585,23586)	union all	select '-'+COLUMN02,'['+COLUMN04+']' from matable014 	where  (" + Session["OPUnitWithNull"] + " or COLUMNA02 is null) AND (COLUMNA03='" + Session["AcOwner"] + "' or COLUMNA03 is null) and isnull(COLUMNA13,0)=0", cn);
                //DataTable dtdata = new DataTable();
                //cmddl.Fill(dtdata);
                //for (int dd = 0; dd < dtdata.Rows.Count; dd++)
                //{
                //    TaxType.Add(new SelectListItem { Value = dtdata.Rows[dd]["COLUMN02"].ToString(), Text = dtdata.Rows[dd]["COLUMN04"].ToString() });
                //}
                TaxType = taxlst.TaxList(ItemId, "", Customer, "Sales", Price, "Tax", Date);

MySmartSCM_APP/eBizSuiteAppUI/Views/ServiceReceipt/PaymentInformationEdit.cshtml
<html>
     <head>  
    <script type="text/javascript" language="javascript">
        var $i = jQuery.noConflict();
        $i(document).ready(function () {
            $i(function () {
                var payamt = $('#initdue').val();
                var acc = document.getElementById("inittax").defaultValue;
                var CardNo = $('#CardNo1').val();
                $('#payacc').find('option:eq(1)').attr('selected', true);
                var totpay = $('#totamt').text();
                var totdue = $('#totdue').text();
                var actpay = $('#IPayAmnt').val();
                var Amttopay = $('#Amttopay').text();
                if (Amttopay == "" || Amttopay == null || typeof (Amttopay) == "undefined") Amttopay = 0;
                if (actpay == "" || actpay == null || typeof (actpay) == "undefined") actpay = 0;
                if (Amttopay > 0) {
                    $('#payamt').val(Amttopay); $('#payamtP').val(actpay);
                    $('#CardNo').val(CardNo);
                    $('#payacc').val(acc);
                }
                else {
                    if (payamt == "" || payamt == null || typeof (payamt) == "undefined") {
                        if (totdue > 0) {
                            $('#payamt').val(totdue);
                            $('#payamtP').val((parseFloat(totpay) - parseFloat(totdue)).toFixed(2));
                            $('#CardNo').val(CardNo);
                            $('#payacc').val(acc);
                        }
                        else {
                            $('#payamt').val(totdue);
                            $('#payamtP').val(totpay);
                            $('#CardNo').val(CardNo);
                            $('#payacc').val(acc);
                        }
                    }
                    else {
                        debugger
                        $('#payamt').val(totdue);
                        $('#payamtP').val((parseFloat(totpay) - parseFloat(totdue)).toFixed(2));
                        $('#CardNo').val(CardNo);
                        $('#payacc').val(acc);
                    }
                }
                if (acc == "" || acc == null || typeof (acc) == "undefined") $('#payacc').val();
                else $('#payacc').val(acc);
            });
            $i('#payacc').on("change", function () {
                var Account = $(this).val();
                $.ajax({
                    url: "/ServiceReceipt/getBalanceAmount?FormName=null",
                    type: "POST",
                    data: JSON.stringify({ Account: Account, FormName: "FormName" }),
                    dataType: "json", cache: true,
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        if (result.Balance != '0') {
                            $('#balamt').text(result.Balance);
                        }
                    }
                })
            });
            $i('#payamt').on("change", function () {
                var balamt = $('#balamt').text();
                var totamt = $i('#totamt').text();
                var payamtP = $i('#payamtP').val();
                var dueAmnt = (parseFloat(totamt) - parseFloat(payamtP));
                var payamt = $(this).val();
                var Amttopay = $('#Amttopay').text();
                if (Amttopay == "" || Amttopay == null || typeof (Amttopay) == "undefined") Amttopay = 0;
                if (balamt == "" || typeof (balamt) == "undefined") balamt = 0;
                if (totamt == "" || typeof (totamt) == "undefined") totamt = 0;
                if (Amttopay > 0) dueAmnt = Amttopay;
                if (isNaN(payamt) || payamt < 0) {
                    Alert.render("Please Enter Value Greater Than Zero Only"); $("#alertok").focus();
                    $("#alertok").on("click", function () {
                        $("#dialogbox").dialog("close"); $('#payamt').focus(); return false;
                    })
                    $('#payamt').val("");
                }
                else if ((parseFloat(payamt) > (parseFloat(dueAmnt) + parseFloat(balamt))) || (parseFloat(payamt) > parseFloat(totamt))) {

                    if ((parseFloat(payamt) > parseFloat(dueAmnt))) {
                        Alert.render("Payment Should Less Than Total Amount Only");
                        $('#payamt').val(dueAmnt);
                        payamt = totamt; $("#alertok").focus();
                        $("#alertok").on("click", function () {
                            $("#dialogbox").dialog("close"); $('#payamt').focus(); return false;
                        })
                    }
                    //if ((parseFloat(payamt) > parseFloat(balamt))) {
                    //    Alert.render("Payment Should Less Than Available Balance Only");
                    //    $('#payamt').val(balamt); $("#alertok").focus();
                    //    $("#alertok").on("click", function () {
                    //        $("#dialogbox").dialog("close"); $('#payamt').focus(); return false;
                    //    })                        
                    //}
                }
            });
            $i('#btnpayok').on("click", function () {
                debugger
                var a = '@Request["ide"]';
                var payamt = $('#payamt').val();
                var payamtP = $('#payamtP').val();
                if (payamtP == "") {
                    $i('#Paymentdlg').dialog('close');
                    Alert.render("There is no Due Amount to Pay");
                    return false;
                }
                var totamt = $i('#totamt').text();
                var payacc = $i('#payacc').val();
                var initamt = $('#initdue').val();
                var due = (parseFloat(totamt) - (parseFloat(payamtP) + parseFloat(payamt))).toFixed(2);
                var tPaid = (parseFloat(payamt) + parseFloat(payamtP)).toFixed(2);
                var Qty = $('#totqty').text();
                var SubTotal = $('#subtot').text();
                var Discount = $('#totdis').text();
                var TaxAmt = $('#tottax').text();
                var Type = $('#Type').val();
                var CardNo = $('#CardNo1').val();
                var Customer = $("input[name=Customer]").val();

                var flag = false;
                if (initamt == "" || typeof (initamt) == "undefined") initamt = 0;
                if (payamt == "" || typeof (payamt) == "undefined") payamt = 0;
                if (totamt == "" || typeof (totamt) == "undefined") totamt = 0;
                if (isNaN(payamt) || payamt < 0) {
                    Alert.render("Please Enter Value Greater Than Zero Only"); $("#alertok").focus(); flag = true;
                    $("#alertok").on("click", function () {
                        $("#dialogbox").dialog("close"); $('#payamt').focus(); return false;
                    })
                    $('#payamt').val("");
                }
                else if ((parseFloat(payamt) > parseFloat(balamt)) || (parseFloat(payamt) > parseFloat(totamt))) {
                    if ((parseFloat(payamt) > parseFloat(totamt))) {
                        Alert.render("Payment Should Less Than Total Amount Only");
                        $('#payamt').val(totamt); flag = true;
                        payamt = totamt; $("#alertok").focus();
                        $("#alertok").on("click", function () {
                            $("#dialogbox").dialog("close"); $('#payamt').focus(); return false;
                        })
                    }
                }
                payamt = $('#payamt').val();
                var Amttopay = $('#Amttopay').text();
                if (Amttopay == "" || Amttopay == null || typeof (Amttopay) == "undefined") Amttopay = 0;
                if (payamt == "" || typeof (payamt) == "undefined") payamt = 0;
                totamt = (parseFloat(totamt) - (parseFloat(payamtP) + parseFloat(payamt))).toFixed(2);
                var totamta = (parseFloat(payamt)).toFixed(2);
                if (Amttopay > 0) {
                    $('#totdue').text(0);
                    $('#dueAmnt').val(0);
                }
                else {
                    $('#totdue').text(totamt);
                    $('#dueAmnt').val(totamt);
                }
                $('#initdue').attr('value', totamta);
                $('#inittax').attr('value', payacc);
                $('#Type').attr('value', Type);
                $('#CardNo1').attr('value', CardNo);


                if (flag == false)
                    $i('#Paymentdlg').dialog('close');
            });
            $i('#btnpaycancel').on("click", function () {
                $i('#Paymentdlg').dialog('close');
            });
        });
        </script>
 </head>
    <body>
        <div style="background-color:#E0ECFF;color:black;width:97%;height:180px;">
       <div style="float:left;width:100%;">
        <div style="padding: 7px;font-size: larger;">Payment Information</div>
        <div id="paymentcal" style="float:left;width:100%;">
            <div style="float: left;width: 100%;padding: 6px;">
            <div style="float: left;width: 45%;padding: 3px;"><div  style="float:left;text-align:right;padding-right:3px;width: 97%;font-size: larger;">Account</div> </div>
            <div style="float: left;width: 45%;"><div style="float:left;width: 28%;text-align: right;">@Html.DropDownList("Account", new SelectList((SelectList)ViewData["Account"], "Value", "Text"), "--Select--", new { @id = "payacc",@style="width: 100px;height: 22px;"})</div></div></div>
        @*    <div style="float: left;width: 100%;"><div style="float: left;width: 45%;padding: 3px;"></div><div  style="float:left;width: 30%;text-align:left;padding-left: 7px;" id="balamt"></div> </div>
            <div style="float: left;width: 100%;padding: 6px;"><div style="float: left;width: 45%;padding: 3px;"><div  style="float:left;text-align:right;padding-right:3px;width: 97%;font-size: larger;">Amount</div> </div>
            <div style="float: left;width: 45%;"><div  style="float:left;width: 30%;text-align: right;"><input type="text" name="payamt" id="payamt" style="width:95px;"/></div></div>
           </div></div>*@
           
            <div style="float: left;width: 100%;"><div style="float: left;width: 45%;padding: 3px;"></div><div  style="float:left;width: 30%;text-align:left;padding-left: 7px;" id="balamt"></div> </div>
            <div style="float: left;width: 100%;padding: 6px;"><div style="float: left;width: 45%;padding: 3px;"><div  style="float:left;text-align:right;padding-right:3px;width: 97%;font-size: larger;">Paid Amount</div> </div>
            <div style="float: left;width: 45%;"><div  style="float:left;width: 30%;text-align: right;"><input type="text" name="payamt" id="payamtP" style="width:95px;" readonly="true"/></div></div>
           </div></div>
            <div style="float: left;width: 100%;"><div style="float: left;width: 45%;padding: 3px;"></div><div  style="float:left;width: 30%;text-align:left;padding-left: 7px;" id="balamt"></div> </div>
            <div style="float: left;width: 100%;padding: 6px;"><div style="float: left;width: 45%;padding: 3px;"><div  style="float:left;text-align:right;padding-right:3px;width: 97%;font-size: larger;">Due Amount</div> </div>
            <div style="float: left;width: 45%;"><div  style="float:left;width: 30%;text-align: right;"><input type="text" name="payamt" id="payamt" style="width:95px;"/></div></div>
           </div>
           
           @if ((Session["TypeChk"].ToString() == "Credit") || (Session["TypeChk"].ToString() == "Debit") || (Session["TypeChk"].ToString() == "Check"))
           {
              <div style="float: left;width: 100%;"><div style="float: left;width: 45%;padding: 3px;"></div><div  style="float:left;width: 30%;text-align:left;padding-left: 7px;" id="balamt1"></div> </div>
            <div style="float: left;width: 100%;padding: 6px;"><div style="float: left;width: 45%;padding: 3px;"><div  style="float:left;text-align:right;padding-right:3px;width: 97%;font-size: larger;">Card No.</div> </div>
            <div style="float: left;width: 45%;"><div  style="float:left;width: 30%;text-align: right;"><input placeholder="Last 4 digits only"  maxlength="4" type="text" name="CardNo" id="CardNo" style="width:95px; " /></div></div>
           </div>  
           }

       </div>

        <div style="float:left;width:100%;">
            <div style="float:right;padding:12px 5px 2px 8px;"><input type='button' name='CANCEL' id='btnpaycancel' value='CANCEL' class='myButton'/></div>
            <div style="float:right;padding:12px 5px 2px 8px;"><input type='button' name='OK' id='btnpayok' value='OK' class='myButton'/></div>
   
            </div>
        </div>
        
    </body>
</html>

MySmartSCM_APP/eBizSuiteAppUI/Views/ServiceReceipt/ServiceReceiptInfo.cshtml
@{
    ViewBag.Title = "Service Receipt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<html>
<head>
     <script src="~/Content/formbuildjquery.js"></script>
 <link href="~/Content/Tabs/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Content/Tabs/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajaxSetup({
            cache: false
        });
        function showDetails() {
            alert("showing some details");
        }
        var tbl = $('#grdfData').DataTable({
            "filter": false,
            "iDisplayLength": 20,
            "pagingType": "simple_numbers",
            "orderClasses": false,
            "order": [[0, "asc"]],
            "info": false,
            "searching": true,
            "scrollCollapse": true,
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "/WebService.asmx/GetTableData?FormName='" + $("#FormName").val() + "'&ViewSort='" + $("#formidi").val() + "'&SortByStatus='0'&ItemType='0'",
            "fnServerData": function (sSource, aoData, fnCallback) {
                aoData.push({ "name": "roleId", "value": "admin" });
                $.ajax({
                    "dataType": 'json',
                    "contentType": "application/json; charset=utf-8",
                    "type": "GET",
                    "url": sSource,
                    "data": aoData,
                    "success": function (msg) {
                        debugger
                        if (msg.d != "") {
                            var json = jQuery.parseJSON(msg.d);
                            fnCallback(json);
                        }
                        else $(".dataTables_processing").css("visibility", "collapse");
                        $("#grdfData").show();
                    },
                    error: function (xhr, textStatus, error) {
                        if (typeof console == "object") {
                            console.log(xhr.status + "," + xhr.responseText + "," + textStatus + "," + error);
                        }
                    }
                });
            },
            fnDrawCallback: function () {
                $('.image-details').bind("click", showDetails);
            }
        });
        $("#infoData").live("click", function () {
            debugger
            $("#divLoading").show();
            var RowNo = $(this).attr('pattern');
            var Query = $(this).attr('itemid'); var FormName = '@Request["FormName"]';
            $.ajax({
                url: "/ServiceReceipt/ItemFullGridFill?FormName=" + FormName + "",
                type: "POST",
                data: JSON.stringify({ Query: Query, FormName: FormName, RowNo: RowNo, Type: 'Next' }),
                dataType: "json", cache: false,
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $('#grdfData').remove();
                    $('#infogridContent').html(data.grid);
                    $('#grdfData').DataTable({
                        "iDisplayLength": 20
                    });
                    if (parseFloat(data.rowscnt) > (parseFloat(RowNo) + 100))
                        $("#infoData").attr('pattern', parseFloat(RowNo) + 100);
                    else
                        $("#infoData").css('display', 'none');
                    $("#infoPrevData").attr('pattern', parseFloat(RowNo) - 1);
                    $("#infoPrevData").css('display', 'block');
                    $("#divLoading").hide();
                }
            });
        });
        $("#infoPrevData").live("click", function () {
            debugger
            $("#divLoading").show();
            var RowNo = $(this).attr('pattern');
            var Query = $(this).attr('itemid'); var FormName = '@Request["FormName"]';
            $.ajax({
                url: "/ServiceReceipt/ItemFullGridFill?FormName=" + FormName + "",
                type: "POST",
                data: JSON.stringify({ Query: Query, FormName: FormName, RowNo: RowNo, Type: 'Prev' }),
                dataType: "json", cache: false,
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $('#grdfData').remove();
                    $('#infogridContent').html(data.grid);
                    $('#grdfData').DataTable({
                        "iDisplayLength": 20
                    });
                    $("#infoData").attr('pattern', parseFloat(RowNo) + 1);
                    $("#infoPrevData").css('display', 'block');
                    $("#infoData").css('display', 'block');
                    if (parseFloat(RowNo) - 100 > 1)
                        $("#infoPrevData").attr('pattern', parseFloat(RowNo) - 100);
                    else
                        $("#infoPrevData").css('display', 'none');
                    $("#divLoading").hide();
                }
            });
        });
    });
    
</script>
</head>
<body>
    <div id="divLoading">
        <p>
            <img src="~/Images/ajax-loading.gif"><br />
            Loading, please wait...
        </p>
    </div>
    <input type="hidden" id="FormName" value="@Session["FormName"]" />
    <input type="hidden" id="formidi" value="@Session["idi"]" />
     <div class="topHeaderContentBodyInfoEmptyCont">
         @{ List<int> permission = Session["Permission"] as List<int>;}
           @{ var infospace = " | ";}
    <div class="rowCont topHeaderContentBodyInfo" id="dynamicinfo">
       <div class="topfirstButtonCont">
                   <div class="btnContleft"><input type="button" class="buttonclass" id="btnList"  value="List"  onclick="@("window.location.href='" + @Url.Action("ServiceReceiptInfo", "ServiceReceipt", new { idi = Request["idi"], FormName = Request["FormName"] }) + "'")    ;  " /></div>
		  <div class="btnContleft">
                @if (permission.Contains(22935))
                { 
              <input type="button" class="buttonclass" id="btnNew"   value="New" onclick="@("window.location.href='" + @Url.Action("ServiceCreate", "ServiceReceipt", new { idi = Request["idi"], FormName = Request["FormName"], ide = "null" }) + "'")    ; " />
                     }
		  </div>
          </div>
        </div>
         
              <div id="Content" class="overflowGrid">
          <table id="grdfData">  
           <thead>
              <tr class="gridStyle">
              @foreach (var result in ViewBag.Columns)
              {
                  if (@result == "ID")
                  {<th></th>
                  }
                  else
                  {
                 <th>@result</th>}
              }
              </tr>
           </thead>
           <tbody></tbody>
        </table></div>
        </div> 
</body>
</html>