MySmartSCM_APP/eBizSuiteAppUI/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eBizSuiteAppModel.Table;
using System.Data.Entity;
using MvcMenuMaster.Models;
using System.ComponentModel.DataAnnotations;

namespace MvcMenuMaster.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/
        public eBizSuiteTableEntities db = new eBizSuiteTableEntities();
        public ActionResult Index()
        {
            return View();
        }
        static List<eBizSuiteTableEntities> Menu = new List<eBizSuiteTableEntities>();
        
        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(MenuItems menu)
        {
            string Parent1 = Request["Parent"];
                MenuItems items = new MenuItems();
                Menu_Master menu1 = new Menu_Master();
                int centerid = Convert.ToInt32(Request["CenterId"]);
                string MenuName = Request["MenuName"];
                int ModuleId = Convert.ToInt32(Request["ModuleId"]);
                string Parent = Request["Parent"];
                //int? Parent = Convert.ToInt32(Request["Parent"]);
                int PriorityLevel = Convert.ToInt32(Request["PriorityLevel"]);
                string IsEnable = Request["IsEnable"];
                string IsFormApplicable = Request["IsFormApplicable"];
                eBizSuiteTableEntities dc = new eBizSuiteTableEntities();
                //var db1 = dc.MenuMasters.Where(a => a.MenuName == Parent).ToList();
                var db1 = dc.Menu_Master.Where(a => a.MenuName == Parent).ToList();
                menu1.CenterId = centerid;
                menu1.MenuName = MenuName;
                menu1.ModuleId = ModuleId;
                if (string.IsNullOrEmpty(Parent)||Parent=="null")
                {
                    menu1.Parent = null;
                }
                else
                {
                int mid=db1.First().MenuId;
                    int cent = (mid);
                    menu1.Parent = cent;
                }
                menu1.PriorityLevel = PriorityLevel;
                menu1.IsEnable = IsEnable;
                menu1.IsFormApplicable = IsFormApplicable;
                db.Menu_Master.Add(menu1);
                db.SaveChanges();
                ViewBag.Message = "Data has been saved succeessfully";
                return RedirectToAction("Index");
            //return View();
            //return View("Create", menu);
        }
        public ActionResult DropDown()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Select", Value = "0", Selected = true });
            items.Add(new SelectListItem { Text="101",  Value="1" });
            items.Add(new SelectListItem { Text = "102", Value = "2" });
            items.Add(new SelectListItem { Text = "103", Value = "3" });
            ViewBag.Data = items;
            return View();
        }
    }
}

MySmartSCM_APP/eBizSuiteAppUI/Controllers/TreeViewController.cs
using eBizSuiteAppModel.Table;
using MvcMenuMaster.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MvcMenuMaster.Controllers
{
    public class TreeViewController : Controller
    {
        //
        // GET: /TreeView/
        eBizSuiteTableEntities db = new eBizSuiteTableEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Employees(int? Priority)
        {
            List<CONTABLE003> all = new List<CONTABLE003>();
            eBizSuiteTableEntities dc = new eBizSuiteTableEntities();

            var db = dc.CONTABLE003.Where(a => a.COLUMN05 != null && a.COLUMNA03 == null && a.COLUMN04==101).ToList();
            int co = db.Count();
            ViewBag.count = co;
            all = dc.CONTABLE003.Where(a => a.COLUMNA03 == null && a.COLUMN04 == 101).ToList();
            return View(all);
        }

        public ActionResult Menu()
        {
            var email = Session["LogedeMailId"];
            List<CONTABLE003> all = new List<CONTABLE003>();
            eBizSuiteTableEntities dc = new eBizSuiteTableEntities();
            var db = dc.CONTABLE003.Where(a => a.COLUMN05 != null).ToList();
            var acOwnr = dc.CONTABLE002.Where(a => a.COLUMN08 == email).ToList();
            var acID = acOwnr.Select(a => a.COLUMN02).FirstOrDefault();
            int co = db.Count();
            ViewBag.count = co;
            ViewBag.Data = dc;
            all = dc.CONTABLE003.Where(a => a.COLUMNA03 == acID).ToList();
            Session["LogedeMailId"] = email;
            return View(all);
        }
        [HttpPost]
        public ActionResult Delete(MenuItems menu)
        {
            MenuItems items = new MenuItems();
            List<CONTABLE003> menu1 = new List<CONTABLE003>();
            string mod = NodeText;
            eBizSuiteTableEntities dc = new eBizSuiteTableEntities();
            var db1 = dc.CONTABLE003.Where(a => a.COLUMN05 == mod).ToList();
            menu1 = dc.CONTABLE003.Where(a => a.COLUMN05 == mod).ToList();
            var parent = (db1.Select(a => a.COLUMN06).ToList());
            int? parentNode = Convert.ToInt32(parent[0]);
            var MId = db1.Select(a => a.COLUMN02).ToList();
            int modid = Convert.ToInt32(MId[0]);
            if (parentNode == null || parentNode == 0)
            {
                var db2 = db.CONTABLE003.Where(a => a.COLUMN02 == modid && a.COLUMNA13 == null).ToList();
                for (int c = 0; c < db2.Count; c++)
                {
                    menu1[0].COLUMNA13 = true;
                    var child = db2.FirstOrDefault().COLUMN02;
                    var col2 = dc.CONTABLE003.Where(a => a.COLUMN06 == child && a.COLUMNA13 == null).ToList();
                    for (int i = 0; i < col2.Count; i++)
                    {
                        col2[i].COLUMNA13 = true;
                        dc.SaveChanges();
                        var scol2 = col2[i].COLUMN02;
                        var sub = dc.CONTABLE003.Where(a => a.COLUMN06 == scol2 && a.COLUMNA13 == null).ToList();
                        for (int j = 0; j < sub.Count; j++)
                        {
                            sub[j].COLUMNA13 = true;
                            dc.SaveChanges();
                            var scol3 = sub[j].COLUMN02;
                            var subsub = dc.CONTABLE003.Where(a => a.COLUMN06 == scol3 && a.COLUMNA13 == null).ToList();
                            for (int k = 0; k < subsub.Count; k++)
                            {
                                subsub[k].COLUMNA13 = true;
                                dc.SaveChanges();
                            }
                        }
                    }
                    dc.SaveChanges();
                } dc.SaveChanges();
            }
            else
            {
                menu1[0].COLUMNA13 = true;
                var child = db1.FirstOrDefault().COLUMN02;
                var col2 = dc.CONTABLE003.Where(a => a.COLUMN06 == child && a.COLUMNA13 == null).ToList();
                for (int i = 0; i < col2.Count; i++)
                {
                    col2[i].COLUMNA13 = true;
                    dc.SaveChanges();
                    var scol2 = col2[i].COLUMN02;
                    var sub = dc.CONTABLE003.Where(a => a.COLUMN06 == scol2 && a.COLUMNA13 == null).ToList();
                    for (int j = 0; j < sub.Count; j++)
                    {
                        sub[j].COLUMNA13 = true;
                        dc.SaveChanges(); var scol3 = sub[j].COLUMN02;
                        var subsub = dc.CONTABLE003.Where(a => a.COLUMN06 == scol3 && a.COLUMNA13 == null).ToList();
                        for (int k = 0; k < subsub.Count; k++)
                        {
                            subsub[k].COLUMNA13 = true;
                            dc.SaveChanges();
                        }
                    }
                }
                dc.SaveChanges();
            }
            return RedirectToAction("Employees");
        }
        static string NodeText;
        //[HttpPost]
        public ActionResult Message(string result)
        {
            result = "Node Does Not Created At This Level";
            ViewBag.jscirpt = "<script language='javascript' type='text/javascript'> alert('Node Does Not Created At This Level');</script>";
            return View(result);
        }
        [HttpPost]
        public JsonResult emp(string result)
        {
            NodeText = result;
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Employees(string NodeType, string NodePlace, string NodeName, string IsFormApplicable, string ScreenName)
        {
           
            MenuItems items = new MenuItems();
            CONTABLE003 menu1 = new CONTABLE003();
            string mod = NodeText;
            string NewNode = NodeName;
            string Type = NodeType;
            string Place =NodePlace;
            string FormApplicable = IsFormApplicable;
            string SName =ScreenName;
            eBizSuiteTableEntities dc = new eBizSuiteTableEntities();

            var db1 = dc.CONTABLE003.Where(a => a.COLUMN05 == mod).ToList();
           
           //To Find CenterId
            var ce = dc.CONTABLE003.OrderByDescending((a => a.COLUMN04)).ToList();
            var cent = ce.Max(a => a.COLUMN04);
            int center = Convert.ToInt32(cent); 
            //To Find MenuId
            var me = dc.CONTABLE003.OrderByDescending((a => a.COLUMN02)).ToList();
            var men = me.Max(a => a.COLUMN02);
            int menuid = Convert.ToInt32(men);
            //To Find ModuleId
            var mo = dc.CONTABLE003.OrderByDescending((a => a.COLUMN03)).ToList();
            var modu = mo.Max(a => a.COLUMN03);
            int module = Convert.ToInt32(modu);
            //To Find PriorityLevel
            var pl = dc.CONTABLE003.OrderByDescending((a => a.COLUMN07)).ToList();
            int prl = Convert.ToInt32(pl.Max(a => a.COLUMN07));

            int Plevel = Convert.ToInt32(db1.FirstOrDefault().COLUMN07);
            int moduleid = Convert.ToInt32(db1.FirstOrDefault().COLUMN03);

            menu1.COLUMN02 = (menuid + 1);
            menu1.COLUMN05 = NewNode;
            menu1.COLUMN08 = "Y";
            menu1.COLUMN04 = 101;
            if (IsFormApplicable == "true")
            {
                menu1.COLUMN09 = "Y";
            }
            else
            {
                menu1.COLUMN09 = "N";
            }
            menu1.COLUMN10 = ScreenName;

            if (Type == "ParentNode")
            {
                if (Plevel == 0 )
                {
                    var result = "Node Does Not Created At This Level";
                    return RedirectToAction("Employees");
                }
                else
                {
                    int mid = Convert.ToInt32(db1[0].COLUMN03);
                    menu1.COLUMN03 = mid;
                    var r = db1[0].COLUMN06;
                    menu1.COLUMN06 = (r);
                    var pll = db1[0].COLUMN07;
                    menu1.COLUMN07 = pll;


                    db1[0].COLUMN06 =( menuid + 1);
                     db1[0].COLUMN07 = pll + 1;
                    //dc.SaveChanges();       
                }

            }
            else if (Type == "ChildNode")
            {
                int mid = Convert.ToInt32(db1[0].COLUMN03);
                menu1.COLUMN03 = mid;
                int r =Convert.ToInt32( db1[0].COLUMN02);
                menu1.COLUMN06 = (r);
                var pll = db1[0].COLUMN07;
                menu1.COLUMN07 = Convert.ToInt32(pll+1);
                int or = Convert.ToInt32(db1[0].COLUMN11);
                int co = dc.CONTABLE003.Where(a => a.COLUMN06 == r).Count();
                menu1.COLUMN11 = co + 1;
                menu1.COLUMN10 = ScreenName; dc.CONTABLE003.Add(menu1);
                var FormAppl = dc.CONTABLE003.Where(a => a.COLUMN02 == r).ToList();
                if (ScreenName != null)
                {
                CONTABLE0010 formmaster = new CONTABLE0010();
                var formdata = dc.CONTABLE0010.OrderBy(a => a.COLUMN02 != null).ToList();
                if (formdata == null)
                {
                    formmaster.COLUMN02 = 1001;
                }
                else
                {
                    var fid = formdata[formdata.Count-1].COLUMN02;
                    formmaster.COLUMN02 = (fid + 1);
                    formmaster.COLUMN06 = (fid + 1);
                }
                formmaster.COLUMN03 = mid;
                formmaster.COLUMN04 = ScreenName;
                formmaster.COLUMN05 = "Standard";
                formmaster.COLUMN07 = "0";
                    
                    dc.CONTABLE0010.Add(formmaster);
                }

MySmartSCM_APP/eBizSuiteAppUI/Views/TreeView/ChildrenNode.cshtml
@model MvcMenuMaster.Models.MenuItems

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChildrenNode</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Add Child Node</legend>
    
    
            <div class="editor-label">
                @Html.LabelFor(model => model.MenuName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MenuName)
                @Html.ValidationMessageFor(model => model.MenuName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.CenterId)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.CenterId)
                @Html.ValidationMessageFor(model => model.CenterId)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Parent)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Parent)
                @Html.ValidationMessageFor(model => model.Parent)
            </div>
    
    
            <div class="editor-label">
                @Html.LabelFor(model => model.IsEnable)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IsEnable)
                @Html.ValidationMessageFor(model => model.IsEnable)
            </div>
    
@*            <div class="editor-label">
                @Html.LabelFor(model => model.Delete)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Delete)
                @Html.ValidationMessageFor(model => model.Delete)
            </div>*@
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "OnDemand")
    </div>
</body>
</html>

MySmartSCM_APP/eBizSuiteAppUI/Views/TreeView/Create.cshtml
@model MvcMenuMaster.Models.MenuItems
@*<script src="~/Scripts/jquery-1.8.2.min.js"></script>*@
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm("Create","TreeView", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>User</legend>
        <table><tr>
        
           <td> @Html.LabelFor(m=>m.ParentNodeList)</td>
            <td>@Html.ListBoxFor(x => x.ParentNodeList, new MultiSelectList(ViewBag.Parentlist, "ModuleName"))
                @Html.ListBoxFor(x => x.ParentNodeCode, new MultiSelectList(ViewBag.ParentCode, "ModuleName"))
            </td>
         @*<td>  @Html.DropDownListFor(model => model.ParentNodeList, new MultiSelectList(ViewBag.Parentlist,"ModuleName"), "Select a ParentNode")</td>*@ 

               </tr>
           <tr><td> @Html.LabelFor(m=>m.ChildNodeList)</td>
       @*<td> @Html.DropDownListFor(model => model.ChildNodeList, new SelectList(ViewBag.Childlist,"ModuleName"), "Select a ChildNode") </td>*@

       <td> @Html.ListBoxFor(model => model.ChildNodeList, new MultiSelectList(ViewBag.Childlist,"ModuleName"), "Select a ChildNode") 
           
                @Html.ListBoxFor(x => x.ChildNodeCode, new MultiSelectList(ViewBag.ChildCode, "ModuleName"))
       </td>
           </tr>
       
            <tr><td>@Html.LabelFor(model => model.Enable)</td>
           <td> @Html.DropDownList("Enable",new SelectList (new[] {"--Select--","Y","N"} ))
        </td></tr>
       <tr><td>
            @Html.LabelFor(model => model.Delete)</td>
           <td> @Html.DropDownList("Delete",new SelectList (new[] {"--Select--","Y","N"} ))
        </td></tr>
       <tr><td>
            @Html.LabelFor(model => model.ParentNode)</td>
           <td> @Html.EditorFor(model => model.MenuName) 
               @Html.EditorFor(model => model.CenterId)
        </td></tr>
       <tr><td>
            @Html.LabelFor(model => model.ChildNode)</td>
         <td>   @Html.EditorFor(model => model.MenuName)
             @Html.EditorFor(model => model.CenterId)
        </td></tr>
             <tr><td>
            <input type="submit" value="Save" id="Create"/>&nbsp;&nbsp;
            <input type="submit" value="Cancel" id="btncancel" />
            @*<a href="#" id="lnkcancel">Cancel</a>*@
        </td></tr></table>
    </fieldset>
}

MySmartSCM_APP/eBizSuiteAppUI/Views/TreeView/Employees.cshtml
@using System.Web.UI.WebControls
@model List<eBizSuiteAppModel.Table.CONTABLE003>
@{
    ViewBag.Title = "Menu Master";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
    <script src="@Url.Content("~/Scripts/jquery/jquery-ui.custom.js")" type="text/javascript"></script>
<script src="~/Scripts/jquery.treeview.js"></script>
<script src="~/Scripts/jstree.js"></script>
<script src="~/Scripts/jstree.min.js"></script>
<script src="~/Scripts/tree.jquery.js"></script>
<link href="~/Scripts/jquery.treeview.css" rel="stylesheet" />
     <script src="~/Content/formbuildjquery.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //TreeView Load
        TreeviewLoad();
        //Treeview On Click
        $(".treeview a").click(function () {
            $("a").css("backgroundColor", "");
            $(this).css("backgroundColor", "yellow");
            var dataparam = { MenuName: $(this).text() };
            TreeViewClickEvent(dataparam);
        });
        //Add New Node
        $("#btn").click("click", function () {
            NewNodeAdd();
        });
        //CheckBox Change Event
        $("#cb").change("change", function () {
            var chkval = $(this).attr('checked');
            CheckBoxChange(chkval);
        });
        //Type Of Node Adding
        $("#pn").change("change", function () {
            NodeTypeAdded();
        });
    });
</script>

<style>
    /*Here We will add some css for style our treeview*/
    .collapse
    {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
        user-select: text;
    }

    .expand
    {
        width: 15px;
        user-select: text;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .treeview ul
    {
        font: 14px Arial, Sans-Serif;
        margin: 0px;
        padding-left: 20px;
        list-style: none;
        user-select: toggle;
    }

    .treeview > li > a
    {
        font-weight: bold;
        user-select: element;
    }

    .treeview li
    {
    }

        .treeview li a
        {
            padding: 4px;
            font-size: 12px;
            display: inline-block;
            text-decoration: none;
            width: auto;
        }
</style>
<div>
  
        <div  class="treeviewbgcolor">
            <fieldset>
                <div  class="treeviewheight">
                    @using (Html.BeginForm())
                    { 
                        <div class="tree1" id="Selection">

                            @if (Model != null)
                            {
                                <ul id="chapterFolders" draggable="true" onblur="Selection">

                                    @Treeview1.GetTreeView(Model, Model.FirstOrDefault().COLUMN06)
                                </ul>
                            }
                        </div>
                    }
                </div>
            </fieldset>
        </div>
        <div class="treeviewnodesbgcolor">
           <fieldset > 
                <div  class="treeviewheight">
                    @using (Html.BeginForm())
                    {<div class="treeviewdivs">
                     <div class="treeviewddl">  @Html.DropDownList("NodeType", new SelectList(new[] { "--Select--", "ParentNode", "ChildNode", "Node" }), htmlAttributes: new { id = "pn",@class="reportddl" }) </div> 
                     <div class="treeviewddl">   @Html.DropDownList("NodePlace", new SelectList(new[] { "--Select--", "After", "Before" }), htmlAttributes: new { id = "ab",@class="reportddl"  })</div> 
                    </div><div class="treeviewdivs">
                        <div class="menulbl">@Html.Label("NodeName")</div>  
                        <input type="text" name="NodeName" id="NodeName" class="statictxt" /></div>
                       <div class="treeviewdivs"><div class="menulbl"> @Html.Label("Is FormApplicable")</div>
                            @Html.CheckBox("IsFormApplicable", false, htmlAttributes: new { id = "cb", @class = "chk" })</div>
                       <div class="treeviewdivs"><div class="menulbl">
                            @Html.Label("Screen Name")</div>    
                             @Html.TextBox("ScreenName", Model.Last().COLUMN10, htmlAttributes: new { id = "txt1", disabled = "disabled", @class = "statictxt" })</div>
                        
                     <div  class="menubuttons">   <input type="submit"  value="Create"  class="buttonclass"  onclick='@Url.Action("Employees", "TreeView")' /></div>
                    }@using (Html.BeginForm("Delete", "TreeView", FormMethod.Post))
            {
               <div class="menubuttons">  <input type="submit"  value="Delete" class="buttonclass" onclick='@Url.Action("TreeView")' />   </div>    
            }
                   @* @Html.ActionLink("Menu", "Menu", "TreeView")*@
               
            </div> </fieldset>
        </div>

</div>
    <script>
        $(document).ready(function () {
            $(".treeview li>ul").css('display', 'none'); // Hide all 2-level ul 
            $(".collapsible").click(function (e) {
                e.preventDefault();
                $(this).toggleClass("collapse expand");
                $(this).closest('li').children('ul').slideToggle();
                $(this).select('li');

            });
        });
    </script>

@*@section Scripts{
}*@

MySmartSCM_APP/eBizSuiteAppUI/Views/TreeView/Menu.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    @*<script src="@Url.Content("~/Scripts/jquery/jquery-ui.custom.js")" type="text/javascript"></script>*@
    <link href="~/Content/jqsimplemenu.css" rel="stylesheet" />
    @*<script src="~/Content/jquery-1.6.2.min.js"></script>*@
    <script src="~/Content/jqsimplemenu.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
  @Html.Partial("_Layout")
        
</head>

<body>
    <div style="vertical-align:top"></div>
   @* @RenderBody()*@
</body>

   <script type="text/javascript">
       $(document).ready(function () {
           $('.menu').jqsimplemenu();
       });
</script>
</html>

MySmartSCM_APP/eBizSuiteAppUI/Views/TreeView/OnDemand.cshtml
@model List<eBizSuiteAppModel.Table.MenuMaster>
@*@model MvcMenuMaster.Controllers.TreeViewController*@
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OnDemand</title>
    <script src="~/Scripts/jquery.jstree.js"></script>
    <link href="~/Scripts/jquery.treeview.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script type="text/javascript">
  </script>

<body>
   <div style="border:1px solid black; padding:0px;  background-color:#FAFAFA">
                @{
                    <div class="treeview" id="toggle">
                        @{
                                   
                                    for (int i = 0; i < ViewBag.count; i++)
                                    {
                           <ul>
                                        
                                            @if (@Model[i].Parent == null)
                                            {
                                             <li> <ul>
                                             <span class="collapse collapsible" data-loaded="false" pid=" @Html.DisplayFor(model => model)">@Model[i].MenuName</span></ul> </li>
                                             
                                                for (int k = 0; k < ViewBag.count; k++)
                                                    {
                                                      if (@Model[i].CenterId == @Model[k].Parent)
                                                       {
                                                        <ul > 
                                                            <li>
                                                           <span class="leaf" >   @Model[k].MenuName
                                                           </span></li>
                                                        </ul>
                                                       }
                                                    }
                                            }                                        
                                </ul>
                                    }
                                            }
                    </div>
                                    }
            </div>
                @Html.ActionLink("Add ParentNode", "ParentNode","TreeView")| 
                            
                @Html.ActionLink("Add ChildrenNode", "ChildrenNode","TreeView") |
                            
                @Html.ActionLink("Custom", "Custom","TreeView")|
                 @Html.ActionLink("Menu", "Menu","TreeView")
     @using (Html.BeginForm("OnDemand", "TreeView", FormMethod.Post))
         {
    <fieldset><legend>Custom Treeview</legend>
        <div>
             <input type="submit"  value="Create" /> 
            &nbsp;&nbsp;&nbsp;@Html.DropDownList("NodeType",new SelectList(new[] {"--Select--","ParentNode","ChildNode"})) 
      &nbsp;&nbsp;&nbsp; @Html.DropDownList("NodePlace",new SelectList(new[] {"--Select--","After","Before"}))
            <div>@Html.Label("MenuName")
              @* @Html.DisplayFor(MvcMenuMaster.Models.MenuItems)*@
     @Html.TextBox("MenuName")</div>
          <div>@Html.Label("NodeName")
     @Html.TextBox("NodeName")</div>
        </div>
    </fieldset>
     }
</body>
</html>