MySmartSCM_APP/eBizSuiteAppUI/Controllers/EmpVsRoleController.cs
using eBizSuiteAppModel.Table;
using eBizSuiteDAL;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Xml;
using WebMatrix.Data;
using System.Configuration;
namespace MvcApplication1.Controllers
{
    public class EmpVsRoleController : Controller
    {

        eBizSuiteTableEntities db = new eBizSuiteTableEntities();
        string sqlcon = ConfigurationManager.ConnectionStrings["sqlcon"].ToString();
        string connectionString = ConfigurationManager.ConnectionStrings["sqlcon"].ToString();
        string providerName = "System.Data.SqlClient";

        //
        // GET: /OperatingUnit/

        string[] theader;
        string[] theadertext;

        public ActionResult Index(string ShowInactives)
        {
            try
            {

                List<WebGridColumn> cols = new List<WebGridColumn>();
                List<WebGridColumn> Inlinecols = new List<WebGridColumn>();
                var tid = db.CONTABLE004.Where(a => a.COLUMN04 == "CONTABLE027").First();
                var ttid = tid.COLUMN02;
                var viewlist = db.CONTABLE013.Where(a => a.COLUMN03 == "Default" && a.COLUMN04 == ttid).ToList();
                var viewsdata = db.CONTABLE013.Where(a => a.COLUMN03 != null && a.COLUMN04 == ttid).ToList();
                ViewBag.views = viewsdata.Select(a => a.COLUMN03).Distinct().ToList();
                var Acolslist = viewlist.Select(a => a.COLUMN06).ToList();
                var Ccolslist = viewlist.Select(a => a.COLUMN07).ToList();
                theader = new string[Acolslist.Count];
                theadertext = new string[Acolslist.Count];
                for (int a = 0; a < Acolslist.Count; a++)
                {
                    var acol = Acolslist[a].ToString();
                    var columnslist = db.CONTABLE005.Where(b => b.COLUMN03 == ttid).ToList();
                    var columndata = columnslist.Where(b => b.COLUMN05 == acol).FirstOrDefault();

                    var tblcol = columndata.COLUMN04;
                    var dcol = Ccolslist[a].ToString();
                    if (a == 0)
                    {
                        cols.Add(new WebGridColumn()
                        {
                            ColumnName = tblcol,
                            Header = "Action",
                            Format = (item) => new HtmlString("<a href=/EmpVsRole/Edit/" + item[tblcol] + " >Edit</a>|<a href=/EmpVsRole/Details/" + item[tblcol] + " >View</a>")

                        });
                        cols.Add(new WebGridColumn()
                        {
                            ColumnName = tblcol,
                            Header = dcol
                        });
                        Inlinecols.Add(new WebGridColumn()
                        {
                            ColumnName = tblcol,
                            Header = dcol,
                            Format = (item) => new HtmlString("<input type='text' id=" + tblcol + " name=" + tblcol + "    Value=" + item[tblcol] + " readonly=true   ''  />")
                        });
                    }
                    else
                    {
                        cols.Add(new WebGridColumn()
                        {
                            ColumnName = tblcol,
                            Header = dcol
                        });
                        Inlinecols.Add(new WebGridColumn()
                        {
                            ColumnName = tblcol,
                            Header = dcol,
                            Format = (item) => new HtmlString("<input type='text' id=" + tblcol + " name=" + tblcol + "    Value=" + item[tblcol] + "  '' />")
                        });
                    } theader[a] = tblcol; theadertext[a] = dcol;

                }
                ViewBag.cols = cols;
                ViewBag.Inlinecols = Inlinecols;
                ViewBag.columns = theader;
                ViewBag.itemscol = theader;
                ViewBag.theadertext = theadertext;
                var ac = Convert.ToInt32(Session["AcOwner"]); string ounit = null;
                if (ac != 56567)
                    ounit = " (p.COLUMNA02 in(" + Session["OPUnit"] + ") or p.COLUMNA02 is null) ";
                else
                    ounit = "  p.COLUMNA02 is null ";
                var query1 = "Select p.COLUMN02,e.COLUMN06 COLUMN03,r.COLUMN04,d.COLUMN04 COLUMN06,o.COLUMN03 COLUMN05,p.COLUMN07 from CONTABLE027 p left outer join MATABLE002 d on d.COLUMN02=p.COLUMN06 left outer join CONTABLE007 o on o.COLUMN02=p.COLUMN05 left outer join CONTABLE012 r on r.COLUMN02=p.COLUMN04 left outer join MATABLE010 e on e.COLUMN02=p.COLUMN03 where p.COLUMNA13='False'    AND p.COLUMN03='" + Session["eid"] + "' AND " + ounit + " AND p.COLUMNA03='" + Session["AcOwner"] + "'";
                var db2 = WebMatrix.Data.Database.Open("sqlcon");
                var books = db2.Query(query1);
                var acO = Convert.ToInt32(Session["AcOwner"]);
                ViewBag.itemsdata = books;
                Session["cols"] = cols;
                Session["Inlinecols"] = Inlinecols;
                return View("Index");
            }
            catch (Exception ex)
            {
                return Content("Form Editing Failed <a onclick='history.go(-1); return false;' href=''> Back</a>");
            }
        }
        //
        // GET: /OperatingUnit/Details/5

        public ActionResult CustomForm()
        {
            try
            {

                var tid = db.CONTABLE004.Where(a => a.COLUMN04 == "CONTABLE027").First();
                var ttid = tid.COLUMN02;
                List<CONTABLE006> all = new List<CONTABLE006>();
                var alll = db.CONTABLE006.Where(a => a.COLUMN04 == ttid && a.COLUMN06 != null && a.COLUMN06 != "").ToList();
                all = alll.Where(a => a.COLUMN06 != null).ToList();
                var Tab = all.Where(a => a.COLUMN11 == "Tab" && a.COLUMN06 != null && a.COLUMN06 != "").ToList();
                var Ta = Tab.Select(a => a.COLUMN12).Distinct().ToList();
                var type = all.Select(b => b.COLUMN11).Distinct();
                var sn = all.Select(b => b.COLUMN12).Distinct();
                var Section = all.Where(b => b.COLUMN11 != "Tab" && b.COLUMN11 != "Item Level" && b.COLUMN06 != null && b.COLUMN06 != "").ToList();
                var sec = Section.Select(b => b.COLUMN12).Distinct();
                //var roles = db.CONTABLE012.Where(a => a.COLUMN04 != null).ToList();
                //ViewBag.Roles = roles;
                ViewBag.Type = type;
                ViewBag.Tabs = sn;
                ViewBag.TabMaster = Ta;
                ViewBag.Section = sec;
                return View(all);
            }
            catch (Exception ex)
            {
                return Content("Form Editing Failed <a onclick='history.go(-1); return false;' href=''> Back</a>");
            }
        }

        public void Normal()
        {

            List<WebGridColumn> cols = new List<WebGridColumn>();
            var col2 = "COLUMN02";
            cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN02",
                Header = "Action",
                Format = (item) => new HtmlString("<a href=/OperatingUnit/Edit/" + item[col2] + " >Edit</a>|<a href=/OperatingUnit/Details/" + item[col2] + " >View</a>")
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN02",
                Header = "OperatingUnit ID"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN03",
                Header = "Name"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN04",
                Header = "Description"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN05",
                Header = "Logo"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN08",
                Header = "Parent Of"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN10",
                Header = "Attention"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN23",
                Header = "RState"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN24",
                Header = "RZip"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN26",
                Header = "Info1"
            }); cols.Add(new WebGridColumn()
            {
                ColumnName = "COLUMN27",
                Header = "Info2"
            });
            ViewBag.cols = cols;

        }

        [HttpGet]
        public ActionResult Sort(string ShowInactives)
        {
            try
            {

                var data = Session["Data"];
                var item = Session["sortselected"];
                ViewBag.sortselected = item;

                return View("Index", data);
            }
            catch (Exception ex)
            {
                return Content("Something went wrong <a onclick='history.go(-1); return false;' href=''> Back</a>");
            }
        }

        //
        // GET: /OperatingUnit/Details/5

        public ActionResult Details(int id = 0)
        {
            try
            {

                CONTABLE027 CONTABLE027 = db.CONTABLE027.Find(id);
                ViewBag.r = db.CONTABLE012.ToList();
                ViewBag.o = db.CONTABLE007.ToList();
                ViewBag.e = db.MATABLE010.ToList();

MySmartSCM_APP/eBizSuiteAppUI/Views/EmpVsRole/Create.cshtml
@model eBizSuiteAppModel.Table.CONTABLE027

@{ ViewBag.Title = "Employee vs Role";
}
<html >
<head >
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title></title>
     <script src="~/Content/formbuildjquery.js"></script>
  <script>
      $(document).ready(function () {
          if ('@Session["DDDynamicItems"]' == 'DDDynamicItems') {
              { Layout = null; }
          }
          $('#form-reset').live('click', function () {
              $(this).formReset();
              return false;
          });
          //Form Save
          $('#btnSave').click(function () {
              EmpRoleSave(document.getElementById("myid1").value);
          })
      })
</script>
</head>
    @using (Html.BeginForm("Create", "EmpVsRole", FormMethod.Post, new { id = "myid1", enctype = "multipart/form-data" }))
    { 
        @Html.ValidationSummary(true)
        if(Session["DDDynamicItems"] != "DDDynamicItems"){
           <div class="rowCont bottomRowContentFB"  id="ddl">
        <div class="bottomColFB1">
            <input type="button" class="buttonclass" id="btnList"  value="List"  onclick="@("window.location.href='" + @Url.Action("Index", "EmpVsRole") + "'")    ;" />
           </div>  
            @if (Session["DDDynamicItems"] != "DDDynamicItems")
            {
           <div class="bottomColFB1">   <input type="submit" name="Save" value="Save"   class="buttonclass"/></div>
            <div class="bottomColFB1">   <input type="submit" name="SaveNew" value="Save & New"   class="buttonclass"/></div>
        @* <div class="bottomColFB1"> <input type="button" value="Cancel"  class="buttonclass" onclick="@("window.location.href='" + @Url.Action("Index", "EmpVsRole") + "'")    ;" /></div>*@
           <div class="bottomColFB1">   <input onclick="$(this).formReset()" id="form-reset" class='buttonclass' type="reset" value="Reset"  /></div>
            }
            @if (Session["DDDynamicItems"] == "DDDynamicItems")
            {
        <div class="bottomColFB1"> <input onclick="@("window.location.href='" + @Url.Action("SetVariable", "FormBuilding") + "'")    ;" id="formreset" class='buttonclass' type="reset" value="Cancel"  /></div>
            } 
        </div>
        }
         <div  id="Staticdiv" class="bodyFBContent">
                <div class="mainRow">
            <div class="mainRowCon">
            <div class="lbl">  @Html.Label("ID#")
                   </div>
             <div class="txt">
                         @Html.TextBoxFor(model => model.COLUMN02, new { @readonly = "readonly",@class="txtclass"  })
                         @Html.ValidationMessageFor(model => model.COLUMN02)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Employee")
                        </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN03, new SelectList(ViewBag.e, "Column02", "Column06"), "select a Item", new {@class="ddl" })
                         @Html.ValidationMessageFor(model => model.COLUMN03)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Role")
                       </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN04, new SelectList(ViewBag.r, "Column02", "Column03"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN04)
                    </div>  </div></div>
                <div class="mainRow"><div class="mainRowCon">
            <div class="lbl">    @Html.Label("Department")
                        </div>
             <div class="txt">   @Html.DropDownListFor(model => model.COLUMN06, new SelectList(ViewBag.d, "Column02", "Column04"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN06)
                </div></div>
            <div class="mainRowCon">
            <div class="lbl">   @Html.Label("Operating Unit")
                      </div>
             <div class="txt">  @Html.DropDownListFor(model => model.COLUMN05, new SelectList(ViewBag.o, "Column02", "Column03"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN05)
               </div>  </div> <div class="mainRowCon">
             <div class="lbl">  @Html.Label("Inactive Flag")
                       </div>
             <div class="txt"> @Html.CheckBoxFor(model => model.COLUMN07)
                          @Html.ValidationMessageFor(model => model.COLUMN07)
                </div>  </div> </div></div>
         <div class="newbottomRowContentFooter" id="footerInfo">

         </div>
    }
@section Scripts {
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
}
    </html>

MySmartSCM_APP/eBizSuiteAppUI/Views/EmpVsRole/CustomView.cshtml
@model IList<eBizSuiteAppModel.Table.CONTABLE005>
@{
    ViewBag.Title = "Employee vs Role";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomView</title>
     <script src="~/Content/formbuildjquery.js"></script>
     <script type="text/javascript">
         $(document).ready(function () {
             //Custom View Save
            $("#ViewSave").click("click", function () {
                EmpRoleCustomViewSave();
            });});
        $(document).ready(function () {
            var fixHelperModified = function (e, tr) {
                var $originals = tr.children();
                var $helper = tr.clone();
                $helper.children().each(function (index) {
                    $(this).width($originals.eq(index).width())
                });
                return $helper;
            },
    updateIndex = function (e, ui) {
        $('td.index', ui.item.parent()).each(function (i) {
            $(this).html(i + 1);
        });
    };

            $("#sort tbody").sortable({
                helper: fixHelperModified,
                stop: updateIndex
            }).disableSelection();
        });
        </script>
</head>
<body>
       <div id="FormData" class="bodyFBContent">
      <div  class="overflowGridCustView">
         @{
             var grid = new WebGrid(Model, canPage: false, canSort: false);
            <div id="sort">
               @grid.GetHtml(tableStyle: "webgrid-table",
                headerStyle: "webgrid-header",
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-row-style", htmlAttributes: new { id = "griddata" },
                columns: grid.Columns(
                grid.Column(columnName: "FieldName", header: "FieldName", format: @<text><input type="text" id="LabelName" value="@item.COLUMN05" disabled="disabled"/></text>),
                grid.Column(columnName: "LabelName", header: "LabelName", format: @<text><input type="text" id="Label" value="@item.COLUMN05" /></text>),
                grid.Column(columnName: "Display", header: "Display", format: @<text>@Html.DropDownList("Action", new SelectList(new[] {  "N","Y" }), htmlAttributes: new {id="ddlact" })</text>)
                ))
            </div> 
        } 
        </div>
        </div>
     <div class="rowCont bottomRowContentFooter" id="footerInfo">
    @Html.Label("ViewName", new { @class="customviewlbl" })
    @Html.TextBox("ViewName","", new { @class="txtclassF" })
          <input type="button" class="buttonclass" value="Save" id="ViewSave"/>
     <input type="button" class="buttonclass" id="FormBuild"  value="Cancel"  onclick="@("window.location.href='" + @Url.Action("Index", "EmpVsRole") + "'")    ;" />
    </div> 
</body>
</html>

MySmartSCM_APP/eBizSuiteAppUI/Views/EmpVsRole/Details.cshtml
@model eBizSuiteAppModel.Table.CONTABLE027

@{
    ViewBag.Title = "Employee vs Role";
}

<header>
     <script src="~/Content/formbuildjquery.js"></script>    
    <script>
        $(document).ready(function () {
            //Emp vs Role Delete
            $('#btnDelete').click(function () {
                EmpRoleDelete(document.getElementById("myid").value);
            })
        });
    </script>


</header>
    @using (Html.BeginForm("Details", "EmpVsRole", FormMethod.Post, new { enctype = "multipart/form-data" }))
    { 
        @Html.ValidationSummary(true)
         <div class="rowCont bottomRowContentFB"  id="ddl">
        <div class="bottomColFB1"> <input type="button" class="buttonclass" id="btnList"  value="List"  onclick="@("window.location.href='" + @Url.Action("Index", "EmpVsRole") + "'")    ;" />
           </div>  
             <div class="bottomColFB1">  <input type="button" class="buttonclass" id="btnEdit"  value="Edit"  onclick="@("window.location.href='" + @Url.Action("/Edit/"+Model.COLUMN02+"") + "'")    ;" /></div>  
        </div> 
         <div  id="Staticdiv" class="bodyFBContent">
                <div class="mainRow">
            <div class="mainRowCon">
            <div class="lbl">  @Html.Label("Emp Vs Role ID")
                   </div>
             <div class="txt">
                         @Html.TextBoxFor(model => model.COLUMN02, new { @readonly = "readonly",@class="txtclass"  })
                         @Html.ValidationMessageFor(model => model.COLUMN02)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Employee")
                        </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN03, new SelectList(ViewBag.e, "Column02", "Column06"), "select a Item", new { @disabled = "disabled",@class="ddl" })
                         @Html.ValidationMessageFor(model => model.COLUMN03)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Role")
                       </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN04, new SelectList(ViewBag.r, "Column02", "Column03"), "select a Item", new { @disabled = "disabled",@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN04)
                    </div>  </div></div>
               <div class="mainRow"><div class="mainRowCon">
            <div class="lbl">    @Html.Label("Department")
                        </div>
             <div class="txt">   @Html.DropDownListFor(model => model.COLUMN06, new SelectList(ViewBag.d, "Column02", "Column04"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN06)
                </div></div>
            <div class="mainRowCon">
            <div class="lbl">   @Html.Label("Operating Unit")
                      </div>
             <div class="txt">  @Html.DropDownListFor(model => model.COLUMN05, new SelectList(ViewBag.o, "Column02", "Column03"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN05)
               </div>  </div> <div class="mainRowCon">
             <div class="lbl">  @Html.Label("Inactive Flag")
                       </div>
             <div class="txt"> @Html.CheckBoxFor(model => model.COLUMN07)
                          @Html.ValidationMessageFor(model => model.COLUMN07)
                </div>  </div> </div></div>
         <div class="newbottomRowContentFooter" id="footerInfo">
               @*<input type="button" value="Back"  class="buttonclass" onclick="@("window.location.href='" + @Url.Action("Index", "OperatingUnit") + "'")    ;" />*@
           </div>
    }

MySmartSCM_APP/eBizSuiteAppUI/Views/EmpVsRole/Edit.cshtml
@model eBizSuiteAppModel.Table.CONTABLE027

@{
    ViewBag.Title = "Employee vs Role";
}

<header>
     <script src="~/Content/formbuildjquery.js"></script>
    
    <script>
        $(document).ready(function () {
            //Emp vs Role Delete
            $('#btnDelete').click(function () {
                EmpRoleDelete(document.getElementById("myid").value)
            })
        });
    </script>

</header>

@using (Html.BeginForm("Edit", "EmpVsRole", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.ValidationSummary(true)
     <div class="rowCont bottomRowContentFB"  id="ddl">
        <div class="bottomColFB1">
                    <input type="button" class="buttonclass" id="btnList"  value="List"  onclick="@("window.location.href='" + @Url.Action("Index", "EmpVsRole") + "'")    ;" />
           </div>   
         <div class="bottomColFB1"><input type="submit" name="Save" value="Save"  class="buttonclass" /></div>
             @*<div class="bottomColFB1"><input type="button" value="Cancel"  class="buttonclass" onclick="@("window.location.href='" + @Url.Action("Index", "OperatingUnit") + "'")    ;" /></div>*@
         <div class="bottomColFB1"><input @*onclick="$(this).formclear()"*@ id="form-reset" class='buttonclass' type="button" value="Reset"  /></div>
         <div class="bottomColFB1"><input type="button" name="Delete" id="btnDelete" value="Delete"  class="buttonclass" /></div>
        </div>
    <div  id="Staticdiv" class="bodyFBContent">
                <div class="mainRow">
            <div class="mainRowCon">
            <div class="lbl">  @Html.Label("Emp Vs Role ID")
                   </div>
             <div class="txt">
                         @Html.TextBoxFor(model => model.COLUMN02, new { @readonly = "readonly",@class="txtclass"  })
                         @Html.ValidationMessageFor(model => model.COLUMN02)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Employee")
                        </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN03, new SelectList(ViewBag.e, "Column02", "Column06"), "select a Item", new {@class="ddl" })
                         @Html.ValidationMessageFor(model => model.COLUMN03)
                </div>  </div> <div class="mainRowCon">
             <div class="lbl"> @Html.Label("Role")
                       </div>
             <div class="txt"> @Html.DropDownListFor(model => model.COLUMN04, new SelectList(ViewBag.r, "Column02", "Column03"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN04)
                    </div>  </div></div>
                <div class="mainRow"><div class="mainRowCon">
            <div class="lbl">    @Html.Label("Department")
                        </div>
             <div class="txt">   @Html.DropDownListFor(model => model.COLUMN06, new SelectList(ViewBag.d, "Column02", "Column04"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN06)
                </div></div>
            <div class="mainRowCon">
            <div class="lbl">   @Html.Label("Operating Unit")
                      </div>
             <div class="txt">  @Html.DropDownListFor(model => model.COLUMN05, new SelectList(ViewBag.o, "Column02", "Column03"), "select a Item", new {@class="ddl" })
                          @Html.ValidationMessageFor(model => model.COLUMN05)
               </div>  </div> <div class="mainRowCon">
             <div class="lbl">  @Html.Label("Inactive Flag")
                       </div>
             <div class="txt"> @Html.CheckBoxFor(model => model.COLUMN07)
                          @Html.ValidationMessageFor(model => model.COLUMN07)
                </div>  </div> </div></div>
         <div class="newbottomRowContentFooter" id="footerInfo">
        </div>
}

@section Scripts {
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
}

MySmartSCM_APP/eBizSuiteAppUI/Views/EmpVsRole/Search.cshtml
@model IEnumerable<eBizSuiteAppModel.Table.CONTABLE007>

@{
    ViewBag.Title = "Operating Unit";
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>  
    
</head>
<body>
 <div id="FormData" >
          @using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
<div class="dialogSearch">
                <div class="searchRow">
                <div class="lbl"> @Html.Label("OperatingUnit ID")</div>
            <div class="txt">
             <input type="text" name="OperatingUnit ID" value="@Request["COLUMN02"]" class="txtclass"/>
               </div></div> <div class="searchRow">
                <div class="lbl">
            @Html.Label("Name")</div>
            <div class="txt">
             <input type="text" name="Name" value="@Request["COLUMN03"]" class="txtclass"/>
            </div></div> <div class="searchRow">
                <div class="lbl">
            @Html.Label("Addressee")</div>
            <div class="txt">
             <input type="text" name="Addressee" value="@Request["COLUMN12"]" class="txtclass"/></div>
           </div></div>
              <div class="popUpSearchFooter">
            <input type="submit" class="buttonclass" id="btn" value="Search"  style="font-size:small"/>
            <button   name="ClientCancel" type="button" class="buttonclass" onclick=" document.location.href = $('#cancelUrl').attr('href');">Cancel</button>
            <a id="cancelUrl" href="@Html.AttributeEncode(Url.Action("Index", "OperatingUnit"))" style="display:none;"></a>
        </div>
} 
    </div>
</body>
</html>